---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "postgres:16.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-default-config
                  key: db_name
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-default-config
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgress-admin-password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
              readOnly: false
              subPath: pgdata
          resources:
            limits:
              cpu: 100m
              memory: 2Gi
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: managed-database-disk
      nodeSelector:
        agentpool: agentpool
