# This is an older config. Deployment is done now via Helm charts.
---
apiVersion: v1
kind: Service
metadata:
  name: nessie-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: nessie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 19120
      name: ui
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: management
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nessie
spec:
  serviceName: nessie-service
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
        - name: nessie
          image: ghcr.io/projectnessie/nessie:0.99.0
          ports:
            - containerPort: 19120
          env:
            - name: NESSIE_VERSION_STORE_TYPE
              value: JDBC2
            - name: NESSIE_SERVER_DEFAULT_BRANCH
              value: main
            - name: NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE
              value: postgresql
            - name: QUARKUS_DATASOURCE_POSTGRESQL_JDBC_URL
              value: jdbc:postgresql://postgres-service.default.svc.cluster.local:5432/nessie
            - name: QUARKUS_DATASOURCE_POSTGRESQL_USERNAME
              value: nessie
            - name: QUARKUS_DATASOURCE_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nessie-secret
                  key: postgres_password
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
      nodeSelector:
        agentpool: agentpool
