apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/component: spark-executor # Custom label from template
    azure.workload.identity/use: "true"  
spec:
  # This is a partial definition. 
  # The full spec will be completed by the Spark server when executors are launched.
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "worker"
      effect: "NoSchedule"
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
  
  nodeSelector:
    agentpool: workerpool 
  