---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managed-database-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 10Gi
