apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-connect-server-rolebinding
  namespace: spark-jobs
subjects:
- kind: ServiceAccount
  name: spark-sa
  namespace: spark-jobs
roleRef:
  kind: Role
  name: spark-connect-server-role
  apiGroup: rbac.authorization.k8s.io
