configOverrides:
  secret: |
    SECRET_KEY = ${superset_secret} # Need to create this
bootstrapScript: |
  #!/bin/bash
  pip install trino
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
