apiVersion: apps/v1
kind: Deployment
metadata:
  name: betfair-trader
  namespace: default
  labels:
    azure.workload.identity/use: "true" # Enable Azure Workload Identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betfair-trader
  template:
    metadata:
      labels:
        app: betfair-trader
    spec:
      serviceAccountName: betfair-trader-service-account
      containers:
        - name: betfair-trader
          image: bettingakscontainerregistry.azurecr.io/betfair_trader:1.5.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: betfair
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: betfair
                  key: password
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: betfair
                  key: app-key
            - name: BET_SIZE
              value: "250"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "betfair-secret-provider"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
