---
apiVersion: v1
kind: Service
metadata:
  name: betfair-trader-website-service
spec:
  selector:
    app: betfair-trader-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: ui
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: betfair-trader-website
  namespace: default
  labels:
    azure.workload.identity/use: "true" # Enable Azure Workload Identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betfair-trader-website
  template:
    metadata:
      labels:
        app: betfair-trader-website
    spec:
      serviceAccountName: betfair-trader-service-account
      containers:
        - name: betfair-trader
          image: bettingakscontainerregistry.azurecr.io/betfair_trader_website:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: betfair
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: betfair
                  key: password
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: betfair
                  key: app-key
            - name: BET_SIZE
              value: "250"
            - name: AZURE_CLIENT_ID
              value: "cad42587-a966-47ec-9b38-07a7fd9b0b00"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "betfair-secret-provider"
