apiVersion: apps/v1
kind: Deployment
metadata:
  name: betfair-trader
  namespace: default
  labels:
    azure.workload.identity/use: "true" # Enable Azure Workload Identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betfair-trader
  template:
    metadata:
      labels:
        app: betfair-trader
    spec:
      serviceAccountName: betfair-trader-service-account
      containers:
        - name: betfair-trader
          image: bettingakscontainerregistry.azurecr.io/betfair_trader:1.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "redis-service"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
