apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: betfair-secret-provider
  namespace: default
spec:
  secretObjects:
    - secretName: betfair
      type: Opaque
      data:
        - objectName: betfair-username
          key: username
        - objectName: betfair-password
          key: password
        - objectName: betfair-app-key
          key: app-key
  provider: azure
  parameters:
    usePodIdentity: "false" # Use Workload Identity
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: cad42587-a966-47ec-9b38-07a7fd9b0b00
    keyvaultName: betfair-trader-kv
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: betfair-username
          objectType: secret
        - |
          objectName: betfair-password
          objectType: secret
        - |
          objectName: betfair-app-key
          objectType: secret
    tenantId: a0b325c9-d9c2-4a61-ba5f-46c9ea3a61d8
