name: Deploy Nessie Cataog
on: [workflow_dispatch]
env:
    RG_NAME: "betting-lakehouse"
    RG_LOCATION: "westeurope"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@main

        - name: Log into Azure
          uses: azure/login@v2
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Create Resource Group'
          uses: azure/cli@v2
          with:
            inlineScript: |
                az group create \
                --name ${{env.RG_NAME}}\
                --location ${{env.RG_LOCATION}}
                
        - name: 'Deploy Bicep file'
          uses: azure/cli@v2
          with:
            inlineScript: |
                az deployment group create \
                --resource-group ${{env.RESOURCE_GROUP}} \
                --template-file /provision/bicep/nessie-containerapp/main.bicep \
                --parameters /provision/bicep/nessie-containerapp/main.bicepparam \
                --parameters dbPasswordSecretValue='${{ secrets.NESSIE_DB_USER_PASSWORD }}'